@startuml
'https://plantuml.com/class-diagram

class DispatcherServlet
class SimpleControllerHandlerAdapter
interface HandlerAdapter
interface Controller
class ServletWrappingController

DispatcherServlet -> HandlerAdapter

SimpleControllerHandlerAdapter ..|> HandlerAdapter
SimpleControllerHandlerAdapter -> Controller
ServletWrappingController ..|> Controller

@enduml