select "t85"."f00" as "计算字段(2)",
        "t85"."f0" as "订单id的计数",
        t85"."订单状态",
        t62"."f0" as "下单时间(日粒度)", "
        t62"."f00" as "计算字段(1)" "
        from "
        "( "  
        "select "  
        "  "t21"."f0", "  
        "  "t61"."f00", "  
        "  coalesce("t21"."订单状态", "  
        "  '') as "f2", "  
        "  ("t21"."订单状态") is not null as "f3" "  
        "from "  
        "  ( "  
        "  select "  
        "    "t11"."f0", "  
        "    "t11"."订单状态", "  
        "    coalesce("t11"."订单状态", "  
        "    '') as "f2", "  
        "    ("t11"."订单状态") is not null as "f3", "  
        "    coalesce("t11"."f0", "  
        "    TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f4", "  
        "    ("t11"."f0") is not null as "f5" "  
        "  from "  
        "    ( "  
        "    select "  
        "      "t1"."f0", "  
        "      "t1"."订单状态", "  
        "      coalesce("t1"."订单状态", "  
        "      '') as "f2", "  
        "      ("t1"."订单状态") is not null as "f3", "  
        "      coalesce("t1"."f0", "  
        "      TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f4", "  
        "      ("t1"."f0") is not null as "f5" "  
        "    from "  
        "      ( "  
        "      select "  
        "        DATE_TRUNC('day', "  
        "        "商品订单表"."下单时间") as "f0", "  
        "        "商品订单表"."订单状态", "  
        "        coalesce("商品订单表"."订单状态", "  
        "        '') as "f2", "  
        "        ("商品订单表"."订单状态") is not null as "f3", "  
        "        coalesce(DATE_TRUNC('day', "  
        "        "商品订单表"."下单时间"), "  
        "        TRY_CAST('1970-01-01 00:00:00' as TIMESTAMP)) as "f4", "  
        "        (DATE_TRUNC('day', "  
        "        "商品订单表"."下单时间")) is not null as "f5" "  
        "      from "  
        "        "PG_DEMO"."零售电商"."商品订单表" as "商品订单表" "  
        "      group by "  
        "        DATE_TRUNC('day', "  
        "        "商品订单表"."下单时间"), "  
        "        "商品订单表"."订单状态") as "t1" "  
        "    left join ( "  
        "      select "  
        "        coalesce("t3"."订单状态", "  
        "        '') as "f0", "  
        "        ("t3"."订单状态") is not null as "f1", "  
        "        coalesce("t3"."f0", "  
        "        TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f2", "  
        "        ("t3"."f0") is not null as "f3" "  
        "      from "  
        "        ( "  
        "        select "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表0"."下单时间") as "f0", "  
        "          "商品订单表0"."订单状态" "  
        "        from "  
        "          "PG_DEMO"."零售电商"."商品订单表" as "商品订单表0" "  
        "        group by "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表0"."下单时间"), "  
        "          "商品订单表0"."订单状态") as "t3" "  
        "      left join ( "  
        "        select "  
        "          "t7"."f0", "  
        "          "t4"."订单状态" "  
        "        from "  
        "          ( "  
        "          select "  
        "            "商品订单表1"."订单状态", "  
        "            DATE_TRUNC('day', "  
        "            "商品订单表1"."下单时间") as "f1" "  
        "          from "  
        "            "PG_DEMO"."零售电商"."商品订单表" as "商品订单表1") as "t4" "  
        "        inner join ( "  
        "          select "  
        "            DATE_ADD('month', "  
        "            1, "  
        "            DATE_TRUNC('day', "  
        "            "商品订单表2"."下单时间")) as "f0", "  
        "            DATE_TRUNC('day', "  
        "            "商品订单表2"."下单时间") as "f00" "  
        "          from "  
        "            "PG_DEMO"."零售电商"."商品订单表" as "商品订单表2" "  
        "          group by "  
        "            DATE_TRUNC('day', "  
        "            "商品订单表2"."下单时间")) as "t7" on "  
        "          "t4"."f1" = "t7"."f00" "  
        "        group by "  
        "          "t7"."f0", "  
        "          "t4"."订单状态") as "t9" on "  
        "        "t3"."f0" is not distinct "  
        "      from "  
        "        "t9"."f0" "  
        "        and "t3"."订单状态" is not distinct "  
        "      from "  
        "        "t9"."订单状态") as "t10" on "  
        "      "t1"."f2" = "t10"."f0" "  
        "      and "t1"."f3" = "t10"."f1" "  
        "      and "t1"."f4" = "t10"."f2" "  
        "      and "t1"."f5" = "t10"."f3") as "t11" "  
        "  left join ( "  
        "    select "  
        "      coalesce("t13"."订单状态", "  
        "      '') as "f0", "  
        "      ("t13"."订单状态") is not null as "f1", "  
        "      coalesce("t13"."f0", "  
        "      TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f2", "  
        "      ("t13"."f0") is not null as "f3" "  
        "    from "  
        "      ( "  
        "      select "  
        "        DATE_TRUNC('day', "  
        "        "商品订单表3"."下单时间") as "f0", "  
        "        "商品订单表3"."订单状态" "  
        "      from "  
        "        "PG_DEMO"."零售电商"."商品订单表" as "商品订单表3" "  
        "      group by "  
        "        DATE_TRUNC('day', "  
        "        "商品订单表3"."下单时间"), "  
        "        "商品订单表3"."订单状态") as "t13" "  
        "    left join ( "  
        "      select "  
        "        "t17"."f0", "  
        "        "t14"."订单状态" "  
        "      from "  
        "        ( "  
        "        select "  
        "          "商品订单表4"."订单状态", "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表4"."下单时间") as "f1" "  
        "        from "  
        "          "PG_DEMO"."零售电商"."商品订单表" as "商品订单表4") as "t14" "  
        "      inner join ( "  
        "        select "  
        "          DATE_ADD('month', "  
        "          1, "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表5"."下单时间")) as "f0", "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表5"."下单时间") as "f00" "  
        "        from "  
        "          "PG_DEMO"."零售电商"."商品订单表" as "商品订单表5" "  
        "        group by "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表5"."下单时间")) as "t17" on "  
        "        "t14"."f1" = "t17"."f00" "  
        "      group by "  
        "        "t17"."f0", "  
        "        "t14"."订单状态") as "t19" on "  
        "      "t13"."f0" is not distinct "  
        "    from "  
        "      "t19"."f0" "  
        "      and "t13"."订单状态" is not distinct "  
        "    from "  
        "      "t19"."订单状态") as "t20" on "  
        "    "t11"."f2" = "t20"."f0" "  
        "    and "t11"."f3" = "t20"."f1" "  
        "    and "t11"."f4" = "t20"."f2" "  
        "    and "t11"."f5" = "t20"."f3") as "t21" "  
        "left join ( "  
        "  select "  
        "    "t58"."f0" as "f00", "  
        "    coalesce("t24"."订单状态", "  
        "    '') as "f1", "  
        "    ("t24"."订单状态") is not null as "f2", "  
        "    coalesce("t24"."f0", "  
        "    TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f3", "  
        "    ("t24"."f0") is not null as "f4" "  
        "  from "  
        "    ( "  
        "    select "  
        "      DATE_TRUNC('day', "  
        "      "商品订单表6"."下单时间") as "f0", "  
        "      "商品订单表6"."订单状态", "  
        "      coalesce("商品订单表6"."订单状态", "  
        "      '') as "f2", "  
        "      ("商品订单表6"."订单状态") is not null as "f3", "  
        "      coalesce(DATE_TRUNC('day', "  
        "      "商品订单表6"."下单时间"), "  
        "      TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f4", "  
        "      (DATE_TRUNC('day', "  
        "      "商品订单表6"."下单时间")) is not null as "f5" "  
        "    from "  
        "      "PG_DEMO"."零售电商"."商品订单表" as "商品订单表6" "  
        "    group by "  
        "      DATE_TRUNC('day', "  
        "      "商品订单表6"."下单时间"), "  
        "      "商品订单表6"."订单状态") as "t24" "  
        "  left join ( "  
        "    select "  
        "      case "  
        "        when TRY_CAST("t52"."f2" is not distinct "  
        "      from "  
        "        0 as BOOLEAN) then null "  
        "        else TRY_CAST(TRY_CAST(case "  
        "          when ("t57"."f2") is null then TRY_CAST(0 as BIGINT) "  
        "          else TRY_CAST("t57"."f2" as BIGINT) "  
        "        end as BIGINT) - TRY_CAST("t52"."f3" as BIGINT) as DOUBLE precision) / TRY_CAST("t52"."f20" as DOUBLE precision) "  
        "      end as "f0", "  
        "      coalesce("t52"."订单状态", "  
        "      '') as "f1", "  
        "      ("t52"."订单状态") is not null as "f2", "  
        "      coalesce("t52"."f0", "  
        "      TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f3", "  
        "      ("t52"."f0") is not null as "f4" "  
        "    from "  
        "      ( "  
        "      select "  
        "        "t51"."f2", "  
        "        "t51"."f3", "  
        "        "t51"."f20", "  
        "        "t26"."订单状态", "  
        "        "t26"."f0" "  
        "      from "  
        "        ( "  
        "        select "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表7"."下单时间") as "f0", "  
        "          "商品订单表7"."订单状态" "  
        "        from "  
        "          "PG_DEMO"."零售电商"."商品订单表" as "商品订单表7" "  
        "        group by "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表7"."下单时间"), "  
        "          "商品订单表7"."订单状态") as "t26" "  
        "      left join ( "  
        "        select "  
        "          MAX(TRY_CAST("t39"."f00" as BIGINT)) as "f2", "  
        "          MAX(TRY_CAST("t48"."f0" as BIGINT)) as "f3", "  
        "          MAX(TRY_CAST("t39"."f00" as BIGINT)) as "f20", "  
        "          "t39"."f0", "  
        "          "t39"."订单状态" "  
        "        from "  
        "          ( "  
        "          select "  
        "            "t29"."f0", "  
        "            "t29"."订单状态", "  
        "            "t38"."f0" as "f00", "  
        "            coalesce("t29"."订单状态", "  
        "            '') as "f3", "  
        "            ("t29"."订单状态") is not null as "f4", "  
        "            coalesce("t29"."f0", "  
        "            TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f5", "  
        "            ("t29"."f0") is not null as "f6" "  
        "          from "  
        "            ( "  
        "            select "  
        "              DATE_TRUNC('day', "  
        "              "商品订单表8"."下单时间") as "f0", "  
        "              "商品订单表8"."订单状态", "  
        "              coalesce("商品订单表8"."订单状态", "  
        "              '') as "f2", "  
        "              ("商品订单表8"."订单状态") is not null as "f3", "  
        "              coalesce(DATE_TRUNC('day', "  
        "              "商品订单表8"."下单时间"), "  
        "              TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f4", "  
        "              (DATE_TRUNC('day', "  
        "              "商品订单表8"."下单时间")) is not null as "f5" "  
        "            from "  
        "              "PG_DEMO"."零售电商"."商品订单表" as "商品订单表8" "  
        "            group by "  
        "              DATE_TRUNC('day', "  
        "              "商品订单表8"."下单时间"), "  
        "              "商品订单表8"."订单状态") as "t29" "  
        "          left join ( "  
        "            select "  
        "              case "  
        "                when ("t37"."f2") is null then TRY_CAST(0 as BIGINT) "  
        "                else TRY_CAST("t37"."f2" as BIGINT) "  
        "              end as "f0", "  
        "              coalesce("t31"."订单状态", "  
        "              '') as "f1", "  
        "              ("t31"."订单状态") is not null as "f2", "  
        "              coalesce("t31"."f0", "  
        "              TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f3", "  
        "              ("t31"."f0") is not null as "f4" "  
        "            from "  
        "              ( "  
        "              select "  
        "                DATE_TRUNC('day', "  
        "                "商品订单表9"."下单时间") as "f0", "  
        "                "商品订单表9"."订单状态" "  
        "              from "  
        "                "PG_DEMO"."零售电商"."商品订单表" as "商品订单表9" "  
        "              group by "  
        "                DATE_TRUNC('day', "  
        "                "商品订单表9"."下单时间"), "  
        "                "商品订单表9"."订单状态") as "t31" "  
        "            left join ( "  
        "              select "  
        "                "t35"."f0", "  
        "                "t32"."订单状态", "  
        "                COUNT("t32"."订单id") as "f2" "  
        "              from "  
        "                ( "  
        "                select "  
        "                  "商品订单表10"."订单状态", "  
        "                  "商品订单表10"."订单id", "  
        "                  DATE_TRUNC('day', "  
        "                  "商品订单表10"."下单时间") as "f2" "  
        "                from "  
        "                  "PG_DEMO"."零售电商"."商品订单表" as "商品订单表10") as "t32" "  
        "              inner join ( "  
        "                select "  
        "                  DATE_ADD('month', "  
        "                  1, "  
        "                  DATE_TRUNC('day', "  
        "                  "商品订单表11"."下单时间")) as "f0", "  
        "                  DATE_TRUNC('day', "  
        "                  "商品订单表11"."下单时间") as "f00" "  
        "                from "  
        "                  "PG_DEMO"."零售电商"."商品订单表" as "商品订单表11" "  
        "                group by "  
        "                  DATE_TRUNC('day', "  
        "                  "商品订单表11"."下单时间")) as "t35" on "  
        "                "t32"."f2" = "t35"."f00" "  
        "              group by "  
        "                "t35"."f0", "  
        "                "t32"."订单状态") as "t37" on "  
        "              "t31"."f0" is not distinct "  
        "            from "  
        "              "t37"."f0" "  
        "              and "t31"."订单状态" is not distinct "  
        "            from "  
        "              "t37"."订单状态") as "t38" on "  
        "            "t29"."f2" = "t38"."f1" "  
        "            and "t29"."f3" = "t38"."f2" "  
        "            and "t29"."f4" = "t38"."f3" "  
        "            and "t29"."f5" = "t38"."f4") as "t39" "  
        "        left join ( "  
        "          select "  
        "            case "  
        "              when ("t47"."f2") is null then TRY_CAST(0 as BIGINT) "  
        "              else TRY_CAST("t47"."f2" as BIGINT) "  
        "            end as "f0", "  
        "            coalesce("t41"."订单状态", "  
        "            '') as "f1", "  
        "            ("t41"."订单状态") is not null as "f2", "  
        "            coalesce("t41"."f0", "  
        "            TRY_CAST('1970-01-01 00:00:00' as timestamp)) as "f3", "  
        "            ("t41"."f0") is not null as "f4" "  
        "          from "  
        "            ( "  
        "            select "  
        "              DATE_TRUNC('day', "  
        "              "商品订单表12"."下单时间") as "f0", "  
        "              "商品订单表12"."订单状态" "  
        "            from "  
        "              "PG_DEMO"."零售电商"."商品订单表" as "商品订单表12" "  
        "            group by "  
        "              DATE_TRUNC('day', "  
        "              "商品订单表12"."下单时间"), "  
        "              "商品订单表12"."订单状态") as "t41" "  
        "          left join ( "  
        "            select "  
        "              "t45"."f0", "  
        "              "t42"."订单状态", "  
        "              COUNT("t42"."订单id") as "f2" "  
        "            from "  
        "              ( "  
        "              select "  
        "                "商品订单表13"."订单状态", "  
        "                "商品订单表13"."订单id", "  
        "                DATE_TRUNC('day', "  
        "                "商品订单表13"."下单时间") as "f2" "  
        "              from "  
        "                "PG_DEMO"."零售电商"."商品订单表" as "商品订单表13") as "t42" "  
        "            inner join ( "  
        "              select "  
        "                DATE_ADD('month', "  
        "                1, "  
        "                DATE_TRUNC('day', "  
        "                "商品订单表14"."下单时间")) as "f0", "  
        "                DATE_TRUNC('day', "  
        "                "商品订单表14"."下单时间") as "f00" "  
        "              from "  
        "                "PG_DEMO"."零售电商"."商品订单表" as "商品订单表14" "  
        "              group by "  
        "                DATE_TRUNC('day', "  
        "                "商品订单表14"."下单时间")) as "t45" on "  
        "              "t42"."f2" = "t45"."f00" "  
        "            group by "  
        "              "t45"."f0", "  
        "              "t42"."订单状态") as "t47" on "  
        "            "t41"."f0" is not distinct "  
        "          from "  
        "            "t47"."f0" "  
        "            and "t41"."订单状态" is not distinct "  
        "          from "  
        "            "t47"."订单状态") as "t48" on "  
        "          "t39"."f3" = "t48"."f1" "  
        "          and "t39"."f4" = "t48"."f2" "  
        "          and "t39"."f5" = "t48"."f3" "  
        "          and "t39"."f6" = "t48"."f4" "  
        "        group by "  
        "          "t39"."f0", "  
        "          "t39"."订单状态") as "t51" on "  
        "        "t26"."f0" is not distinct "  
        "      from "  
        "        "t51"."f0" "  
        "        and "t26"."订单状态" is not distinct "  
        "      from "  
        "        "t51"."订单状态") as "t52" "  
        "    left join ( "  
        "      select "  
        "        "t55"."f2" as "f20", "  
        "        "t55"."订单状态0" as "订单状态00", "  
        "        COUNT("t53"."订单id") as "f2" "  
        "      from "  
        "        ( "  
        "        select "  
        "          "商品订单表15"."订单id", "  
        "          "商品订单表15"."订单状态", "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表15"."下单时间") as "f2" "  
        "        from "  
        "          "PG_DEMO"."零售电商"."商品订单表" as "商品订单表15") as "t53" "  
        "      inner join ( "  
        "        select "  
        "          "商品订单表16"."订单状态", "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表16"."下单时间") as "f1", "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表16"."下单时间") as "f2", "  
        "          "商品订单表16"."订单状态" as "订单状态0" "  
        "        from "  
        "          "PG_DEMO"."零售电商"."商品订单表" as "商品订单表16" "  
        "        group by "  
        "          "商品订单表16"."订单状态", "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表16"."下单时间"), "  
        "          DATE_TRUNC('day', "  
        "          "商品订单表16"."下单时间"), "  
        "          "商品订单表16"."订单状态") as "t55" on "  
        "        "t53"."订单状态" = "t55"."订单状态" "  
        "          and "t53"."f2" = "t55"."f1" "  
        "        group by "  
        "          "t55"."f2", "  
        "          "t55"."订单状态0") as "t57" on "  
        "      "t52"."f0" is not distinct "  
        "    from "  
        "      "t57"."f20" "  
        "      and "t52"."订单状态" is not distinct "  
        "    from "  
        "      "t57"."订单状态00") as "t58" on "  
        "    "t24"."f2" = "t58"."f1" "  
        "    and "t24"."f3" = "t58"."f2" "  
        "    and "t24"."f4" = "t58"."f3" "  
        "    and "t24"."f5" = "t58"."f4" "  
        "  group by "  
        "    "t24"."f0", "  
        "    "t24"."订单状态", "  
        "    "t58"."f0") as "t61" on "  
        "  "t21"."f2" = "t61"."f1" "  
        "  and "t21"."f3" = "t61"."f2" "  
        "  and "t21"."f4" = "t61"."f3" "  
        "  and "t21"."f5" = "t61"."f4") as "t62" "  
        "right join ( "  
        "select "  
        "  "t84"."f0" as "f00", "  
        "  "t74"."f0", "  
        "  "t74"."订单状态", "  
        "  coalesce("t74"."订单状态", "  
        "  '') as "f3", "  
        "  ("t74"."订单状态") is not null as "f4" "  
        "from "  
        "  ( "  
        "  select "  
        "    "t73"."f0", "  
        "    "t66"."订单状态", "  
        "    coalesce("t66"."订单状态", "  
        "    '') as "f2", "  
        "    ("t66"."订单状态") is not null as "f3" "  
        "  from "  
        "    ( "  
        "    select "  
        "      "商品订单表17"."订单状态", "  
        "      coalesce("商品订单表17"."订单状态", "  
        "      '') as "f1", "  
        "      ("商品订单表17"."订单状态") is not null as "f2" "  
        "    from "  
        "      "PG_DEMO"."零售电商"."商品订单表" as "商品订单表17" "  
        "    group by "  
        "      "商品订单表17"."订单状态" "  
        "    order by "  
        "      "商品订单表17"."订单状态" "  
        "limit 1001 ) as "t66" "  
        "  left join ( "  
        "    select "  
        "      case "  
        "        when ("t72"."f1") is null then TRY_CAST(0 as BIGINT) "  
        "        else TRY_CAST("t72"."f1" as BIGINT) "  
        "      end as "f0", "  
        "      coalesce("t69"."订单状态", "  
        "      '') as "f1", "  
        "      ("t69"."订单状态") is not null as "f2" "  
        "    from "  
        "      ( "  
        "      select "  
        "        "商品订单表18"."订单状态" "  
        "      from "  
        "        "PG_DEMO"."零售电商"."商品订单表" as "商品订单表18" "  
        "      group by "  
        "        "商品订单表18"."订单状态" "  
        "      order by "  
        "        "商品订单表18"."订单状态" "  
        "limit 1001) as "t69" "  
        "    left join ( "  
        "      select "  
        "        "商品订单表19"."订单状态", "  
        "        COUNT("商品订单表19"."订单id") as "f1" "  
        "      from "  
        "        "PG_DEMO"."零售电商"."商品订单表" as "商品订单表19" "  
        "      group by "  
        "        "商品订单表19"."订单状态" "  
        "      order by "  
        "        "商品订单表19"."订单状态" "  
        "limit 1001) as "t72" on "  
        "      "t69"."订单状态" is not distinct "  
        "    from "  
        "      "t72"."订单状态") as "t73" on "  
        "    "t66"."f1" = "t73"."f1" "  
        "    and "t66"."f2" = "t73"."f2") as "t74" "  
        "left join ( "  
        "  select "  
        "    case "  
        "      when ("t83"."f1") is null then TRY_CAST(0 as BIGINT) "  
        "      else TRY_CAST("t83"."f1" as BIGINT) "  
        "    end as "f0", "  
        "    coalesce("t78"."订单状态", "  
        "    '') as "f1", "  
        "    ("t78"."订单状态") is not null as "f2" "  
        "  from "  
        "    ( "  
        "    select "  
        "      "商品订单表20"."订单状态" "  
        "    from "  
        "      "PG_DEMO"."零售电商"."商品订单表" as "商品订单表20" "  
        "    where "  
        "      "商品订单表20"."订单id" is not distinct "  
        "    from "  
        "      22713458740 "  
        "    group by "  
        "      "商品订单表20"."订单状态" "  
        "    order by "  
        "      "商品订单表20"."订单状态" "  
        "limit 1001) as "t78" "  
        "  left join ( "  
        "    select "  
        "      COUNT("商品订单表21"."订单id") as "f1", "  
        "      "商品订单表21"."订单状态" "  
        "    from "  
        "      "PG_DEMO"."零售电商"."商品订单表" as "商品订单表21" "  
        "    where "  
        "      TRY_CAST("商品订单表21"."订单id" is not distinct "  
        "    from "  
        "      22713458740 as BOOLEAN) "  
        "    group by "  
        "      "商品订单表21"."订单状态" "  
        "    order by "  
        "      "商品订单表21"."订单状态" "  
        "limit 1001) as "t83" on "  
    "t78"."订单状态" is not distinct "  
  from "  
    "t83"."订单状态") as "t84" on "  
  "t74"."f2" = "t84"."f1" "  
  and "t74"."f3" = "t84"."f2") as "t85" on "  
"t62"."f2" = "t85"."f3" "  
and "t62"."f3" = "t85"."f4" "  
order by "  
"t85"."订单状态",  
("t62"."f0") desc
limit 1001
